# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Run unit tests with coverage
      - name: Run Tests
        run: npm test

      # Upload test results as artifact
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            coverage/
            junit.xml

      # Display test summary in workflow (optional but nice to have)
      - name: Test Summary
        run: |
          echo "Test Results Summary:"
          cat coverage/lcov-report/index.html || true

      # Your existing ESLint step
      - name: Run ESLint
        run: npm run lint

      # Your existing Docker build step
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: mariskah/cin
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
